### ISSUE TITLE
Change the ontology namespace / iri prefix

### ISSUE THREAD

**Issue by SimonStier** [materialdigital/glasdigital-ontology#6]
e. g. to https://w3id.org/pmd/go (conflict with Gene Ontology) or https://w3id.org/pmd/glass-ontology

- https://github.com/perma-id/w3id.org
- https://github.com/perma-id/w3id.org/tree/master/pmd
- https://github.com/materialdigital/w3id

**Comment by Lexachoc** [comment]
Fixed. IRI: https://w3id.org/pmd/glass-ontology
