### ISSUE TITLE
Use same deploy workflow as pmd-core

### ISSUE THREAD

**Issue by SimonStier** [materialdigital/glasdigital-ontology#8]
widoco-1.4.17 exports the xml serialization as `.rdf` while widoco-1.4.19 uses `.owl` => Redirects to not match:
https://github.com/materialdigital/w3id/blob/c4bad3d65e6d3994ff0ad81f2c03c61f509a9c5c/pmd/.htaccess#L20

**Comment by Lexachoc** [comment]
Fixed. Use the same workflow from https://github.com/materialdigital/ontology_publication_template/blob/main/.github/workflows/workflow.yaml 

However java-11-widoco-1.4.17-jar-with-dependencies.jar doesn't output to `public` but `public/doc` in my case. So I did some modification to move the files out from `doc` directory.
